package MusicalElements;

public enum Dynamic {
	PPPPPPPPPP, PPPPPPPPP, PPPPPPPP, PPPPPPP, PPPPPP, PPPPP, PPPP, PPP, PP, P, MP,
	MF, F, FF, FFF, FFFF, FFFFF, FFFFFF, FFFFFFF, FFFFFFFF, FFFFFFFFF, FFFFFFFFFF,
	ERROR
}
