package Dynamics;

public enum dynamic {
	PPPPPPPPPP, PPPPPPPPP, PPPPPPPP, PPPPPPP, PPPPPP, PPPPP, PPPP, PPP, PP, P, MP,
	MF, F, FF, FFF, FFFF, FFFFF, FFFFFF, FFFFFFF, FFFFFFFF, FFFFFFFFF, FFFFFFFFFF,
	ERROR
}
